### PR TITLE
NamedNodeMap & Attr

### PR DESCRIPTION
**Pull request by garyb**
Originally by @flip111, #48

### CODE REVIEW

**Comment by flip111** [comment]
@garyb 

The `name` is missing from `Attr` https://github.com/purescript-web/purescript-web-dom/pull/48/files#diff-7c8aabca817a0ebb12913019e6aed189f70ded5bd7cc693ddef6c0c0f4ff213fR15 Name is listed here https://developer.mozilla.org/en-US/docs/Web/API/Attr#instance_properties

**Comment by flip111** [comment]
@garyb i found another bug in your code

https://github.com/purescript-web/purescript-web-dom/blob/master/src/Web/DOM/DOMTokenList.js#L85-L93

> TypeError: list.tokens is not iterable

The code i had before worked and i tested that it worked https://github.com/flip111/purescript-web-dom/blob/00114fabcf336a6b193fec77b4b8233dee2e591f/src/Web/DOM/DOMTokenList.js#L69-L80

to be honest i'm not happy that you closed my original pull request without comments / review. And that you took it upon yourself to make changes and stuff starts breaking

**Comment by garyb** [comment]
I don't exactly remember now, but I imagine I was trying to being helpful by fixing conflicts with `main`, making `eslint` happy, and changing a bunch of stuff to make the code idiomatic instead of sending it back to you to do so. 🤷‍♂️ Also integrating the `*Name` stuff at the same time rather than doing another pass of that. I probably had limited time and thought if I just do one pass over it at least everything will be sorted rather than it sitting for months with no response from me again.

You're right that I should have tested it though.

**Comment by flip111** [comment]
> I probably had limited time and thought if I just do one pass over it

Depends if you optimize your time for one big pass, or multiple smaller passes. In the latter case i could have done all that and you would just have to review it.

**Pull request merged**
